### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hzmnet** [hexya-erp/hexya#23] opened 2018-03-11 04:48 UTC
Fetching https://golang.org/x/text/transform?go-get=1
https fetch failed: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
Fetching https://golang.org/x/text/unicode/norm?go-get=1
https fetch failed: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
Fetching https://golang.org/x/tools/go/loader?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/loader?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
package golang.org/x/tools/go/loader: unrecognized import path "golang.org/x/tools/go/loader" (https fetch: Get https://golang.org/x/tools/go/loader?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by npiganeau** [comment] 2018-03-11 07:46
Looks like a network error while fetching an external dependency. Try again later.

**Comment by hzmnet** [comment] 2018-03-11 16:22
it is the issue for China because GFW

**Comment by npiganeau** [comment] 2018-03-17 16:17
Since the issue is not directly linked to Hexya, I close it.

**Closed by npiganeau** 2018-03-17 16:17 UTC

**Comment by hzmnet** [comment] 2018-03-20 05:33
will you change the import path for those packages?

**Comment by npiganeau** [comment] 2018-03-20 10:14
They are dependencies of my dependencies and they are official golang packages. So there is not much I can do about it unfortunately.

They have mirrors on GitHub https://github.com/golang/tools and  https://github.com/golang/text, if that can help.
